# Generated by Django 4.1.3 on 2022-11-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='booking.room'),
        ),
    ]
