# Generated by Django 4.1.3 on 2022-11-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_hotel_name_alter_rate_name_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rate',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
