# Generated by Django 3.2 on 2022-11-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_hotel_code_alter_rate_code_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='rate',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='room',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('rate', 'date', 'deleted')},
        ),
    ]
