# Generated by Django 3.2 on 2022-11-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20221130_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='booking.room'),
        ),
    ]
